# version: '3.8'
# services:
#    mongo:
#     image: mongo
#     restart: always
#     ports:
#       - 27018:27017
#     networks:
#       - common-net
#    server:
#         image: krishtopchik/backend
#         build:
#             context: ./
#         ports:
#             - "3000:3000"
#         networks:
#              - common-net
# networks:
#   common-net: {}

version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api: 
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: npm run start:prod
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  mongodb_data_container: